#
# winpty docker run --interactive --tty --rm my-openjdk:latest
#

FROM ubuntu:22.04

# openjdk metadata
ARG JDK_NAME=openjdk-18.0.2
ARG SHA256_CHECKSUM=cf06f41a3952038df0550e8cbc2baf0aa877c3ba00cca0dd26f73134f8baf0e6
ARG DOWNLOAD_LINK=https://download.java.net/java/GA/jdk18.0.2/f6ad4b4450fd4d298113270ec84f30ee/9/GPL/openjdk-18.0.2_linux-x64_bin.tar.gz

# user proxy
ARG MY_UID=1000
ARG MY_GID=1000
RUN groupadd --gid ${MY_GID} vodalus \
    && useradd --create-home --uid ${MY_UID} --gid ${MY_GID} --shell /bin/bash vodalus

# update package index, upgrade and install
RUN apt-get update && apt-get upgrade --assume-yes && apt-get --assume-yes install curl tzdata

# download java, verify checksum, unzip and install it
WORKDIR /home/vodalus
RUN mkdir java
WORKDIR java
RUN curl --output ${JDK_NAME}.tar.gz ${DOWNLOAD_LINK} \
    && sha256sum ${JDK_NAME}.tar.gz | grep ${SHA256_CHECKSUM} \
    && gzip --uncompress ${JDK_NAME}.tar.gz \
    && tar --extract --verbose --file=${JDK_NAME}.tar \
    && DIR_NAME=$(tar --extract --verbose --file=${JDK_NAME}.tar | head --lines=1 | sed --expression='s/\/.*//') \
    && mv ${DIR_NAME} ${JDK_NAME} \
    && rm ${JDK_NAME}.tar \
    && chown --recursive vodalus:vodalus ${JDK_NAME} \
    && update-alternatives --install /usr/bin/java java /home/vodalus/java/${JDK_NAME}/bin/java 1 \
    && update-alternatives --set java /home/vodalus/java/${JDK_NAME}/bin/java
ENV JAVA_HOME=/home/vodalus/java/${JDK_NAME}

WORKDIR /home/vodalus
USER vodalus
